describe('Cadastro de aluno ', function() {
    beforeEach(function () {
        cy.viewport(1440, 900)
        cy.loginIndependente()
    })

    it('Cadastrar um aluno completo, exceto usuário movel', function() {
        cy.get('#atalho-adicionar-aluno').click()
        cy.GeraUmNomeDeAlunoAleatorio()
        //cy.get('#nome-aluno-input').type(nomeCompleto)
        cy.get('#situacao-aluno-select').select('ATIVO')
        cy.get('#nivel-aluno-input').select('2')
        cy.get('#pacto-select-professor').click()
        cy.get('#pacto-select-professor-0').click()
        cy.get('#data-nascimento-input').type('24/12/1992')
        cy.get('#email-input').type('aluno32@pacto.com')
        cy.get('#email-adicionar').click()
        cy.get('#telefone-input').type('(62) 98574-5784')
        cy.get('#telefone-adicionar').click()
        cy.get('#salvar-cadastro-aluno').click()
        cy.contains('Aluno cadastrado com sucesso')
    })

    it('Valida se o campo nome do professor esta obrigatorio', function() {
        cy.get('#atalho-adicionar-aluno').click()
        cy.GeraUmNomeDeAlunoAleatorio()
        cy.get('#situacao-aluno-select').select('ATIVO')
        cy.get('#nivel-aluno-input').select('2')
        cy.get('#salvar-cadastro-aluno').click()
        cy.contains('Campos obrigatórios não preenchidos.')
    })

    it('Cadastro de aluno com usuário movel', function(){
        cy.get('#atalho-adicionar-aluno').click()
        cy.GeraUmNomeDeAlunoAleatorio()
        cy.get('#situacao-aluno-select').select('ATIVO')
        cy.get('#nivel-aluno-input').select('2')
        cy.get('#pacto-select-professor').click()
        cy.get('#pacto-select-professor-0').click()
        cy.get('#data-nascimento-input').type('24/12/1992')
        cy.get('#email-input').type('aluno32@pacto.com')
        cy.get('#email-adicionar').click()
        cy.get('#telefone-input').type('(62) 98574-5784')
        cy.get('#telefone-adicionar').click()
        cy.get('#usarApp').check('')
        cy.get('#username-aluno').type('atotimatizado@pacto.com' + Math.floor(Math.random() * 10000 + 1))
        cy.get('#password-aluno').type('12345')
        cy.get('#salvar-cadastro-aluno').click()
        cy.contains('Aluno cadastrado com sucesso')
    })
    
    it('Cadastro de aluno com usuário movel já existente', function(){
        cy.get('#atalho-adicionar-aluno').click()
        cy.GeraUmNomeDeAlunoAleatorio()
        cy.get('#situacao-aluno-select').select('ATIVO')
        cy.get('#nivel-aluno-input').select('2')
        cy.get('#pacto-select-professor').click()
        cy.get('#pacto-select-professor-0').click()
        cy.get('#data-nascimento-input').type('24/12/1992')
        cy.get('#email-input').type('aluno32@pacto.com')
        cy.get('#email-adicionar').click()
        cy.get('#telefone-input').type('(62) 98574-5784')
        cy.get('#telefone-adicionar').click()
        cy.get('#usarApp').check('')
        cy.get('#username-aluno').type('atotimatizado@pacto.com')
        cy.get('#password-aluno').type('12345')
        cy.get('#salvar-cadastro-aluno').click()
        cy.contains('Nome de usuário duplicado.')
    })
})
           
