describe('Cadastros pelo atalho no cadastro da aula ', function() {

    let codigoAula = Math.random().toString(6).substring(2, 8)
    let codigoModalidade = Math.random().toString(6).substring(2, 8)
    let codigoAmbiente = Math.random().toString(6).substring(2, 8)

    beforeEach(function () {
        cy.viewport(1440, 900)
        cy.loginIndependente()
    })

    it('Cadastra aula, insere uma nova modalidade e ambiente', function(){
        
        cy.visit('novotreino/pt/treino/cadastros/aulas')
        cy.get('#btn-nova-aula').click()
        cy.get('#nome-aula-input').type(`Aula de ` + `${codigoAula}`) 
        cy.get('#btn-add-modalidade').click()
        cy.get('#input-nome-modalidade').type(`Modalidade ` + `${codigoModalidade}`)
        cy.get('#cor-id-10').click()
        cy.get('.modal-footer > #btn-salvar-modalidade').click()
        cy.contains('Modalidade criada com sucesso.')
        cy.get('#professor-select').select('PACTO MÉTODO GESTÃO')
        cy.get('#btn-add-ambiente').click()
        cy.get('#input-nome-ambiente').type(`Ambiente ` + `${codigoAmbiente}`)
        cy.get('#input-capacidade-ambiente').type('100')
        cy.get('#btn-salvar-ambiente').click()
        cy.contains('Ambiente criado com sucesso.')
        cy.get('#tolerancia-aula-input').type('20')
        cy.get('#capacidade-aula-input').type('50')
        cy.get('#segunda-check').check('segunda')
        cy.get('#terca-check').check('terca')
        cy.get('#quarta-check').check('quarta')
        cy.get('#sabado-check').check('sabado')
        cy.get('#horario-aula-input').type('08:30 - 09:00')
        cy.get('#btn-add-horario').click()
        cy.get('#horario-aula-input').type('12:00 - 12:30')
        cy.get('#btn-add-horario').click()
        cy.get('#data-inicio-input').type(Cypress.moment().format('DD/MM/YYYY'))
        cy.get('#data-fim-input').type(Cypress.moment().format('DD/MM/YYYY'))
        cy.get('#btn-add-aula').click()
        cy.contains('Aula criada com sucesso.')
        cy.get('#input-busca-rapida').type(`Aula de ` + `${codigoAula}`)
        cy.wait(1000)
        cy.get('#element-0-edit').click()
        cy.get('#nome-aula-input').should('be.visible')
        cy.contains(`Modalidade ` + `${codigoModalidade}`)
        cy.contains(`Ambiente ` + `${codigoAmbiente}`)
    })
})
